riptide_behavior_tree:
  ros__parameters:
    loop_timeout: 100
    plugins:
      - nav2_recovery_node_bt_node
      - is_battery_lower_than
      - is_pressure_greater_than
      - say_something
      - load_controller
      - unload_controller
      - nav2_single_trigger_bt_node
      - depth_action