riptide:
  controller_manager:
    ros__parameters:
      update_rate: 5  # Hz

      test_battery_card:
        type: riptide_testers/RiptideBatteryCardTester

riptide:
  test_battery_card:
    ros__parameters:
      sensor_name: battery_card