riptide_1:
  controller_manager:
    ros__parameters:
      update_rate: 25  # Hz

      pressure_broadcaster:
        type: riptide_broadcasters/PressureBroadcaster

      battery_card_broadcaster:
        type: riptide_broadcasters/BatteryCardBroadcaster

      depth_controller:
        type: riptide_controllers/DepthController

riptide_1:
  depth_controller:
    ros__parameters:
      thruster_joint: thruster
      p_joint: p_fin
      s_joint: s_fin
      pressure_name: pressure

riptide_1:
  pressure_broadcaster:
    ros__parameters:
      sensor_name: pressure

riptide_1:
  battery_card_broadcaster:
    ros__parameters:
      sensor_name: battery_card