controller_manager:
  ros__parameters:
    update_rate: 25  # Hz

    depth_controller:
      type: riptide_testers/DepthController

test_actuators:
  ros__parameters:
    thruster_joint: thruster
    d_joint: d_fin
    p_joint: p_fin
    s_joint: s_fin
